AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.vendor/**/*'
    - '.git/**/*'

# Temporarily disabled until we can refactor
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Always enabled
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/BlockComments:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Next:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

