#!/bin/bash

base_url='https://api.nexmo.com'
version='/v1'
action='/applications '
application_id='/APPLICATION_ID'
key='API_KEY'
secret='API_SECRET'
name='UpdatedApplication'
type='voice'
answer_url='https://example.com/ncco'
event_url='https://example.com/call_status'

#To update your application, you must include all parameters
curl -X PUT "$base_url$version$action$application_id?api_key=$key&api_secret=$secret&name=$name&type=$type&answer_url=$answer_url&event_url=$event_url"
