#!/bin/bash

# Create an Application for Messages & Dispatch API

  base_url='https://api.nexmo.com'
  version='/v1'
  action='/applications/?'
  key='API_KEY'
  secret='API_SECRET'
  name='MyFirstApplication'
  type='messages'
  status_url='https://example.com/status'
  inbound_url='https://example.com/inbound'

  curl $base_url$version$action \
    -d api_key=$key \
    -d api_secret=$secret \
    -d name=$name \
    -d type=$type \
    -d status_url=$status_url \
    -d inbound_url=$inbound_url
