#!/bin/bash

#Create an Application for Voice API.

  base_url='https://api.nexmo.com'
  version='/v1'
  action='/applications/?'
  key='API_KEY'
  secret='API_SECRET'
  name='MyFirstApplication'
  type='voice'
  answer_url='https://nexmo-community.github.io/ncco-examples/conference.json'
  event_url='https://example.com/call_status'

#In this example, answer_url points to a static NCCO that creates a Conference.

  curl $base_url$version$action \
    -d api_key=$key \
    -d api_secret=$secret \
    -d name=$name \
    -d type=$type \
    -d answer_url=$answer_url \
    -d event_url=$event_url
